import { TableFiltersSelectedType } from '../model/types/tableFiltersSelected';

export const tableSelectedFilters: TableFiltersSelectedType = {
    birthDate: {
        from: null,
        to: null,
    },
    gender: 'null',
    nationality: 'null',
    citizenship: 'null',
    phoneNumber: '',
    speciality: 'null',
    qualifications: 'null',
    studyDurations: ['null'],
    educationsCourses: ['null'],
    educationsForms: 'null',
    arrivalDate: {
        from: null,
        to: null,
    },
    enrollmentTypes: 'null',
    studentArrivalSources: 'null',
    finishedEducationTypes: 'null',
    studyLanguages: 'null',
    hasAccessToExams: false,
    residenceTypes: 'null',
    residentialAddress: '',
    temporaryAddress: '',
    needHostelTypes: ['null'],
    liveAtHostel: false,
    financingSources: ['null'],
    admissionQuotasTypes: ['null'],
    isOrphan: false,
    withoutParentalCare: false,
    isDisabledPerson: false,
    materialAssistanceTypes: ['null'],
    fromYoungFamily: false,
    studyInDualSystem: false,
    studyInSerpin: false,
    studyInProductiveEmployment: false,
    completedTrainingAtCompetenceCenter: false,
    studyInWorldskills: false,
    involvedInSocialActivities: false,
    inYouthAffairsCommittee: false,
    inStudentParliament: false,
    inJasSarbaz: false,
};
